# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04\x61ion\":\n\x10InferenceRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\ninput_data\x18\x02 \x01(\x0c\"N\n\x11InferenceResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\tworker_id\x18\x03 \x01(\t2O\n\x11ModelOrchestrator\x12:\n\x07Predict\x12\x16.aion.InferenceRequest\x1a\x17.aion.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=23
  _globals['_INFERENCEREQUEST']._serialized_end=81
  _globals['_INFERENCERESPONSE']._serialized_start=83
  _globals['_INFERENCERESPONSE']._serialized_end=161
  _globals['_MODELORCHESTRATOR']._serialized_start=163
  _globals['_MODELORCHESTRATOR']._serialized_end=242
# @@protoc_insertion_point(module_scope)
